In [1]:
import numpy as np
import torch

In [9]:
w = torch.Tensor(3,4)
w

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [34]:
# tensor([[-37955820.0000,  -1592520.5000,   -203957.0000]]

a=torch.tensor([[-37955820.0000,  -1592520.5000,   -203957.0000]])/1000000
softmax=torch.nn.Softmax()
relu=torch.nn.ReLU()
fc1=torch.nn.Linear(3,5)
fc1.weight

Parameter containing:
tensor([[-0.4534,  0.3025, -0.2776],
        [-0.4067, -0.0642, -0.1638],
        [ 0.1921, -0.2198, -0.5003],
        [-0.1345, -0.3511, -0.5041],
        [ 0.3314, -0.4759,  0.1622]], requires_grad=True)

In [32]:
softmax(a)

<ipython-input-32-62fba499a704>:1: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  softmax(a)


tensor([[3.2200e-17, 1.9964e-01, 8.0036e-01]])

In [7]:
a=torch.tensor([2,3,4])
a

tensor([2, 3, 4])

In [30]:
torch.normal(mean=0.5, std=torch.arange(1, 6))

RuntimeError: "normal_kernel_cpu" not implemented for 'Long'

In [6]:
a=np.array([[0,0.5,0.5,0.3,0.2,0.5]])
a

array([[0. , 0.5, 0.5, 0.3, 0.2, 0.5]])

In [13]:
np.random.normal(a,3)

array([[-0.76937837,  2.09532264,  0.18429382,  4.27775308, -2.91123644,
        -1.65041654]])

In [4]:
a=np.clip(np.random.normal(a,3),0,1)
a

array([[0.10981178, 0.        , 1.        , 0.2740658 , 1.        ,
        1.        ]])