In [3]:
import numpy as np
import xlwt
e_num=10
user_num=2

In [2]:
for i in range(5):
    print(i)

0
1
2
3
4


In [11]:
for i in range(1,21,4):
    print(i)

1
5
9
13
17


In [27]:
Hn=np.random.randint(1,3)
Hn

2

In [33]:
def get_channel_gain_sum():#共谋
    Hn=np.random.randint(1,3)
    print(Hn)
    Hn_e=2
    while(Hn_e==Hn):
        get_channel_gain_sum()

    return Hn, Hn_e

In [35]:
a,b=get_channel_gain_sum()

2
1
2
2
2
1
2
1
2
2
1
1
1
2
1
2
2
2
2
1
1
2
1
2
1
1
2
2
2
1
2
1
2
1
1
2
2
1
1
1
1
2
1
1
2
1
1
2
2
1
2
1
1
1
2
1
2
2
1
1
2
1
1
2
1
1
2
2
2
2
1
1
2
2
2
2
2
2
1
1
1
2
1
2
1
2
1
1
2
2
2
1
2
2
2
2
2
2
2
1
2
2
2
1
2
1
2
1
2
1
1
1
1
2
1
2
1
2
2
2
1
1
1
1
1
2
1
1
1
1
1
1
2
1
1
2
2
2
1
2
1
1
2
1
1
1
1
1
1
1
1
2
2
1
2
1
2
2
1
2
1
2
1
2
1
1
2
1
2
1
1
2
1
2
2
1
1
1
2
2
2
2
2
1
2
2
1
2
2
2
2
2
2
1
2
1
1
2
1
1
1
1
2
2
2
1
1
1
2
1
2
1
2
2
1
2
1
2
1
1
1
2
1
1
1
2
1
2
2
1
2
2
1
2
1
1
1
1
2
2
1
1
1
1
2
1
1
2
1
1
2
2
1
1
2
1
2
2
2
2
2
1
2
2
1
1
1
1
1
2
2
2
1
1
1
2
2
2
2
2
1
2
2
2
1
2
1
2
1
2
1
2
1
1
2
2
1
2
1
2
1
1
2
1
2
1
1
2
1
2
1
1
1
1
2
1
1
2
2
2
2
1
2
2
2
2
1
1
1
2
1
2
2
1
1
1
2
1
1
2
1
2
2
1
2
2
1
1
1
2
2
2
1
2
2
1
1
1
2
2
1
1
1
2
2
2
1
1
2
2
1
2
1
1
1
1
1
2
1
1
2
2
2
2
1
1
1
2
2
2
2
2
1
1
1
2
1
1
1
2
2
2
1
1
1
2
2
1
2
1
2
1
1
2
2
2
1
1
1
2
2
2
2
2
1
1
2
2
1
1
1
2
1
2
2
2
1
2
2
2
1
1
2
2
1
1
1
2
2
2
1
2
1
1
1
2
1
1
1
2
1
1
1
1
1
1
2
1
2
1
1
2
1
2
2
2
2
2
2
1
2
2
1
2
2
2
1
1
2
2
2
1
1
1
1
2
1
2
1
1


RecursionError: maximum recursion depth exceeded while calling a Python object

In [10]:
env_ch_e = np.sum(env_ch_e, axis=1)  # 共谋取和
env_ch_e

array([0.40717645, 0.37414435])

In [4]:
Hn_e_total=np.zeros(shape=(e_num,user_num))

Hn_e_total[0]

array([0., 0.])

In [16]:
for i in range(e_num):
    Hn_e_total[i]=np.abs(0.1 * np.sqrt(1 / 2) * (np.random.normal(1, 0.1, user_num) + np.complex('j') *
                                           np.random.normal(1, 0.1, user_num))) ** 2
Hn_e_total_sum=np.sum(Hn_e_total,axis=1)
Hn_e_total_sum
index=np.argmax(Hn_e_total_sum)
Hn_e=Hn_e_total[index]

array([0.02269936, 0.01693968, 0.02441666, 0.01975165, 0.02037338,
       0.02184746, 0.02105509, 0.02072791, 0.0190615 , 0.01544152])

In [5]:
np.max(Hn_e1,Hn_e2)

TypeError: only integer scalar arrays can be converted to a scalar index

In [43]:
list_i=[]
for i in range(50):
    list_i.append(i)
list_i

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49]

In [47]:
def data_write(file_path, datas):
    f = xlwt.Workbook()
    sheet1 = f.add_sheet(u'sheet1',cell_overwrite_ok=True) #创建sheet
    #将数据写入第 i 行，第 j 列
    i = 0
    for data in datas:
        for j in range(len(data)):
            sheet1.write(i,j,data[j])
        i = i + 1
    f.save(file_path) #保存文件
data_write("test",list_i)

TypeError: 'int' object is not subscriptable

In [8]:
Hn_e1 = np.abs(0.1 * np.sqrt(1 / 2) * (np.random.normal(1, 0.1, 2) + np.complex('j') *
                                           np.random.normal(1, 0.1, 2))) ** 2
Hn_e1

array([0.00882708, 0.00939827])

In [6]:
Hn = np.abs(1.1 * np.sqrt(1 / 2) * (np.random.normal(1, 0.1, [2, 2]) + np.complex('j') *
                                    np.random.normal(1, 0.1, [2, 2]))) ** 2
Hn[0]

array([1.35882256, 1.2896009 ])